// components/toggler/index.tsx
'use client'

import type { JSX } from 'react'

import { AdButton, useDarkMode } from 'nucleify'

import './_index.scss'

export function NucDarkModeToggler(): JSX.Element {
  const { isDark, toggleDarkMode } = useDarkMode()

  return (
    <AdButton
      aria-label={isDark ? 'Switch to light mode' : 'Switch to dark mode'}
      className="nuc-dark-mode-toggler"
      icon={isDark ? 'prime:moon' : 'prime:sun'}
      rounded
      severity="secondary"
      text
      onClick={toggleDarkMode}
    />
  )
}

// components/toggler/index.vue
<template>
  <ad-button
    class="nuc-dark-mode-toggler"
    :icon="isDark ? 'prime:moon' : 'prime:sun'"
    :aria-label="isDark ? 'Switch to light mode' : 'Switch to dark mode'"
    severity="secondary"
    text
    rounded
    @click="toggleDarkMode()"
  />
</template>

<script setup lang="ts">
import { useDarkMode } from 'nucleify'

const { isDark, toggleDarkMode } = useDarkMode()
</script>

<style lang="scss">
@import 'index';
</style>
